Feature/more information
gen-digital/gendeporte-api-users pull request #2
Opened 2024-02-27 11:39 UTC by Merlinys

Bueno aqui esta lo de agregar nueva informacion ,por el momento como esta hecho ,el orden seria asi :
-Se crea un usuario , y se le agrega aleatoriamente un String en la columna de validationCode
![image](https://github.com/gen-digital/gendeporte-api-users/assets/75582918/b4649832-b883-4230-9682-d3c336d7ffd2)
-Ese codigo se puede saber con el getUser
![image](https://github.com/gen-digital/gendeporte-api-users/assets/75582918/f7b04b88-5973-4edb-9d66-423863b75bf8)
-Con ese codigo se puede verificar un usuario , lo que actualiza la columna updateAt
![image](https://github.com/gen-digital/gendeporte-api-users/assets/75582918/61691268-b597-4bfb-a3c0-d857ba5128b9)
-Al tener esa columna diferente de un null , se puede usar el controlador para agregar mas informacion al usuario
![image](https://github.com/gen-digital/gendeporte-api-users/assets/75582918/3ac3d6ff-37ee-4cdc-8ac8-9851687eb5e1)
Informacion adicional : 
1.por como hice esto me acabo de dar cuenta que el sistema al crear un user tambien actualiza la tabla updateAt lo que hace que se pueda dar mas informacion antes de verificar al user, por solucion a esto simplemente seria agregar otro if para que compruebe que la fecha sea distinta a la fecha de cuando se creo .
2.Por el momento esto esta hecho en el caso exitoso , si falla tira un null por el momento ,luego intento agregar lo relacionado a Exceptions
3.Tambien todavia no lo de encodificar contraseñas por que todavia tengo que ver como modificar bien la configuracion para el passwordEncoder

2024-02-28 13:32 UTC, cmartinezs requested changes
Favor corregir las observaciones. Como observación adicional, los campos json debe ser nombre en formato snake_case, es decir todo en minuscila cada palabra separada por guón bajo **_**

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/endpoint/UsersControllers.java
> +public class UsersControllers {
El nombre del controller es en singular, ya que es una clase

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/endpoint/UsersControllers.java
> +    @PostMapping("/create-users")
no se debe utilizar verbo en el path, como comenté usaremos el nivel de madurez de richarson en nivel 2. la accion está dada por el verbo http, en este caso el POST (crear un nuevo recurso), por lo tanto es redundante usar en el path nuevamente esa palabra, además ya la base del path del controller es /users, por lo que la ruta completa está siendo `POST /users/create-users`, sin embargo lo correcto debe ser `POST /users` simplemente.

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/endpoint/UsersControllers.java
> +    @GetMapping("/search-users")
Lo mismo en este caso, es un simple `GET /users`, que es obtener todos los usuarios. En caso de querer buscar por algun campo en particular lo debemos indicar en el path, por ejemplo `/by-username/{username}`, quedando un path `GET /users/by-username/el_nombre_de_usuario,` de esta forma queda más semantico el servicio, y ademas en este caso el parametro ya seria de tipo `PathVariable` y no `RequestBody`
Por el caso más en general de búsqueda se usan query params, algo como `/users?username=nombre_de_usuario&email=elemail@servicio.com` , etc.

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/endpoint/UsersControllers.java
> +    @PostMapping("/verify-users")
Continuando con lo anterior, aqui utilizaría el path `/verification` o `/email-varification`. Siempre debemos buscar el uso de sustantivos en el path, tomando en consideracion ya la base del controller, es decir no volver a escribir en este caso la palabra users. Además seleccionar bien el verbo, aqui queda más un `PATCH` ya que se modifica el usuario, no estas creando uno nuevo como con el `POST`

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/endpoint/UsersControllers.java
> +    @PostMapping("/moreInfo-users")
como también te comenté, hay que usar paths con nomenclatura hyphen-case, es decir, cada palabra en minuscula, separada por un guión-. Además aplicar lo indicado en los otros comentarios

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/endpoint/UsersControllers.java
> +    public ResponseEntity<BaseResponse> createUser(@RequestBody @Validated PostNewUserRequest request){
debemos ser consistentes en los nomnbres, por ejemplo la funcion es create, pero el request es New.... estandarizemos para que sea más sencillo luego comprender el uso mismo.

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/endpoint/UsersControllers.java
> +        return ResponseEntity.status(HttpStatus.OK).body(toResponse(user,"200","User founded"));
utilizar constantes en vez de literales.

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/endpoint/UsersControllers.java
> +        return ResponseEntity.status(HttpStatus.ACCEPTED).body(toResponseVerify(user,"200","User verified"));
utilizar constantes en vez de literales

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/endpoint/UsersControllers.java
> +        return ResponseEntity.status(HttpStatus.OK).body(toResponseInfo(user,"200","User updated information"));
utilizar constantes en vez de literales

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/endpoint/UsersControllers.java
> +                .success(new MessageResponse("C00", "Success user creation"))
utilizar constantes en vez de literales

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/request/user/post/PostMoreInfoUserRequest.java
> +    private String address;
utilizar de mejor forma las anotaciones de validacion, por ejemplo en un string el `@NotNull `solamente valida que no sea nulo, pero un "" o un " ", o " ", pasan como ok. Existen validadores como `@NotEmpty`, `@Min`, `@Max` para validar vacios o largos de un string.

Fijate que los validadores sean del package javax. no de com.sun., si no aparecen debes agregar el starter de validations de springboot

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/request/user/get/GetUserRequest.java
> +    private String username;
utilizar de mejor forma las anotaciones de validacion, por ejemplo en un string el `@NotNull `solamente valida que no sea nulo, pero un "" o un " ", o " ", pasan como ok. Existen validadores como `@NotEmpty`, `@Min`, `@Max` para validar vacios o largos de un string.

Fijate que los validadores sean del package javax. no de com.sun., si no aparecen debes agregar el starter de validations de springboot

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/request/user/post/PostNewUserRequest.java
> +    private String password;
utilizar de mejor forma las anotaciones de validacion, por ejemplo en un string el `@NotNull `solamente valida que no sea nulo, pero un "" o un " ", o " ", pasan como ok. Existen validadores como `@NotEmpty`, `@Min`, `@Max` para validar vacios o largos de un string.

Fijate que los validadores sean del package javax. no de com.sun., si no aparecen debes agregar el starter de validations de springboot

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/request/user/post/PostVerifyUserRequest.java
> +    private String validationCode;
utilizar de mejor forma las anotaciones de validacion, por ejemplo en un string el `@NotNull `solamente valida que no sea nulo, pero un "" o un " ", o " ", pasan como ok. Existen validadores como `@NotEmpty`, `@Min`, `@Max` para validar vacios o largos de un string.

Fijate que los validadores sean del package javax. no de com.sun., si no aparecen debes agregar el starter de validations de springboot

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/responses/base/BaseResponse.java
> +@SuperBuilder
Esta anotacion solo aplica cuando la clase hereda de otra, lo cual no es este caso

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/core/adapters/service/UserServiceAdapter.java
> +        return userPersistence;
solamente declarar variables cuando se vayan a utilziar, en este caso la instanciacion de la nueva clase se puede retornar inmediatamente

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/core/adapters/service/UserServiceAdapter.java
> +                .orElse(null);
nunca debemos retornar `null`, por una ejecucion de codigo "saludable", además no nos tenemos que preocupar si algo es null luego de usar un metodo si sabemos que no retorna `null`

Por otra parte en estos casos dependiendo de la obligacion del codigo, deberiamos retonar una excepcion ajustada a la situación

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/core/adapters/service/UserServiceAdapter.java
> +                        .orElseThrow(() -> null);
nunca debemos retornar `null`, por una ejecucion de codigo "saludable", además no nos tenemos que preocupar si algo es null luego de usar un metodo si sabemos que no retorna `null`

Por otra parte en estos casos dependiendo de la obligacion del codigo, deberiamos retonar una excepcion ajustada a la situación

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/core/adapters/service/UserServiceAdapter.java
> +            return null;
nunca debemos retornar `null`, por una ejecucion de codigo "saludable", además no nos tenemos que preocupar si algo es null luego de usar un metodo si sabemos que no retorna `null`

Por otra parte en estos casos dependiendo de la obligacion del codigo, deberiamos retonar una excepcion ajustada a la situación

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/core/adapters/service/UserServiceAdapter.java
> +                        .orElseThrow(() -> null);
nunca debemos retornar `null`, por una ejecucion de codigo "saludable", además no nos tenemos que preocupar si algo es null luego de usar un metodo si sabemos que no retorna `null`

Por otra parte en estos casos dependiendo de la obligacion del codigo, deberiamos retonar una excepcion ajustada a la situación

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/core/adapters/service/UserServiceAdapter.java
> +        return null;
nunca debemos retornar `null`, por una ejecucion de codigo "saludable", además no nos tenemos que preocupar si algo es null luego de usar un metodo si sabemos que no retorna `null`

Por otra parte en estos casos dependiendo de la obligacion del codigo, deberiamos retonar una excepcion ajustada a la situación

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/infra/adapters/persistence/jpa/UserJpaAdapter.java
> +        }
esto debe ser una funcion a parte, que es candidata a ser parte de alguna clase de utilidades, hay que diferenciar los responsabilidades de cada funcion, que se dedique a una sola cosa.

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/infra/adapters/persistence/jpa/UserJpaAdapter.java
> +                        .orElseThrow(()->null);
nunca debemos retornar `null`, por una ejecucion de codigo "saludable", además no nos tenemos que preocupar si algo es null luego de usar un metodo si sabemos que no retorna `null`

Por otra parte en estos casos dependiendo de la obligacion del codigo, deberiamos retonar una excepcion ajustada a la situación

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/infra/adapters/persistence/jpa/UserJpaAdapter.java
> +                    .orElseThrow(() -> null);
nunca debemos retornar `null`, por una ejecucion de codigo "saludable", además no nos tenemos que preocupar si algo es null luego de usar un metodo si sabemos que no retorna `null`

Por otra parte en estos casos dependiendo de la obligacion del codigo, deberiamos retonar una excepcion ajustada a la situación

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/infra/persistence/model/jpa/User.java
> +    }
corregir indentación de llaves

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/core/adapters/service/UserServiceAdapter.java
> +        } else {
se puede utilizar el metodo `existsBy...` que ya retorna un boolean, por lo tanto se evita el computo del `isPresent`

Además aqui debiese arrojar una exception ya que se intenta ingresar un usuario que ya existe

2024-02-28 13:32 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/core/adapters/service/UserServiceAdapter.java
> +        if (userPersistencePort.findByUsername(cmd.getUsername()).isPresent() && foundUser.getEnabledAt()!= null) {
esta validacion a pesar de estar bien desde el punto de vista de la logica, está ya que hace un acceso a BD innecesario, ya está la variable foundUser, por lo tanto no es necesario la verificacion por `isPresent`. Además podrias crear un metodo que haga la validacion completa, encontrar por username y que enabledAt sea distinto de null, algo como `findByUsernameAndEnabledAtIsNotNull`

2024-03-02 03:26 UTC, Merlinys commented
hice para responde en caso de excepciones , pero estan sin todo el concepto de Exception handler que me menciono

2024-03-04 06:56 UTC, cmartinezs requested changes

2024-03-04 06:56 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/endpoint/UserControllers.java
> +public class UserControllers {
Aun sigue en plural

2024-03-04 06:56 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/endpoint/UserControllers.java
> +    @PostMapping()
Cuando una anotación no lleva parametros, no son necesarios los paréntesis

2024-03-04 06:56 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/endpoint/UserControllers.java
> +    public ResponseEntity<BaseResponse> verifyUser(@RequestBody PostVerificationRequest request){
El verbo `HTTP` es **PATCH** pero la clase del _request_ utiliza el prefijo `Post`, deben ser consistentes.

2024-03-04 06:56 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/request/user/post/PostCreateUserRequest.java
> +    @NotEmpty
Recordando, los `@NotEmpty `permiten valores como **"      ",** asi que la mejor opción sería `@NotBlank` para que no se permitan valores con espacios en blanco

2024-03-04 06:56 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/request/user/post/PostVerificationRequest.java
> +    private String validation_code;
Los nombres de variables deben ser en camelCase, no en snake_case.

2024-03-04 06:56 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/responses/user/get/GetUserResponse.java
> +    private LocalDateTime updated_at;
Los nombres de variables deben ser camelCase y no snake_case.

2024-03-04 06:56 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/responses/user/get/GetUserResponse.java
> +    private LocalDateTime updated_at;
Creo que esto fue para resolver que las respuestas json sean snake_case, sin embargo en java no son asi. Hay que usar una configuración del conversor java-json que tiene springboot, basado en la libreria Jackson. Se debe utilizar `@JsonProperty`. Puedes ver un ejemplo [aquí](https://www.concretepage.com/jackson-api/jackson-jsonproperty-and-jsonalias-example)

2024-03-04 06:56 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/responses/user/post/PostCreateUserResponse.java
> +    private final Integer user_id;
usar camelCase

2024-03-04 06:56 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/responses/user/post/PostEnrichResponse.java
> +    private final LocalDateTime uptated_at;
usar camelCase

2024-03-04 06:56 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/api/responses/user/post/PostVerificationResponse.java
> +    private final LocalDateTime enabled_at;
usar camelCase

2024-03-04 06:56 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/core/exceptions/GlobalExceptionHandler.java
> +    public ResponseEntity<Object> handleUserNotExist(UserNotExist userNotExist){
Nunca usar el tipo generico Object

2024-03-04 06:56 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/infra/adapters/persistence/jpa/UserJpaAdapter.java
> +        }
Si la funcion evaluada en el if ya retorna un booleano y el bloque del if o el else el retronar el booleano respectivo, no tiene sentido el bloque, basta con retornar el valor de la funcion directamente.

2024-03-04 06:56 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/infra/adapters/persistence/jpa/UserJpaAdapter.java
> +        }
Si la funcion evaluada en el if ya retorna un booleano y el bloque del if o el else el retronar el booleano respectivo, no tiene sentido el bloque, basta con retornar el valor de la funcion directamente.

2024-03-04 06:56 UTC, cmartinezs commented on src/main/java/cl/gendigital/gendeporte/users/infra/utils/UserUtils.java
> +public class UserUtils {
un @Component corresponde a un bean dentro de spring, para que una clase sea un bean es porque necesariamente depende de otro bean, de tal modo que para que se inyecte tambien tiene que se un bean esta clase. Para este caso no existe dependencia de otro bean, por lo que basta con que sea una clase con metodos estaticos, y no sea necesario inyectar a otros beans.

2024-03-05 23:04 UTC, cmartinezs approved these changes
todo ok!

2024-03-05 23:29 UTC, merged